services:
  - type: web
    name: react-three-express
    env: node
    plan: free
    rootDir: .
    buildCommand: |
      cd client
      npm install
      npm run build
      cd ../server
      npm install
    startCommand: |
      node index.js
    autoDeploy: true
